### ISSUE TITLE
support for NT 5.1

### ISSUE THREAD

**Issue by andika207** [andyjsmith/Registry-Spy#1]
this tool doesn't run on Windows XP.

**Comment by andyjsmith** [comment]
The latest version of Python that works on Windows XP is 3.4; this program requires 3.8+. So unfortunately Windows XP is not a supported host OS.

**Comment by andika207** [comment]
so if I get it right, you could compile the source code with Python 3.4 and get it to work for XP users but you apparently have no interest in it....

**Comment by andyjsmith** [comment]
I don't think you understand. It's not that I don't have interest, but the program will not work in Python 3.4. f-strings, other language features, etc. are missing in 3.4. The whole backbone of the program, [PySide6](https://pypi.org/project/PySide6/), only supports Python 3.6+. The program would have to be completely rewritten to support 3.4, which I am not going to do. Not to mention 3.4 is EOL.
