### ISSUE TITLE
Registry Spy v1.1.0 does not run in Windows 10

### ISSUE THREAD

**Issue by aquila-XP** [andyjsmith/Registry-Spy#5]
Previous version of Registry Spy (1.0.2) was working fine in Windows 10 Enterprise 2015 LTSB x64.
Now, when running the Registry Spy v1.1.0 I get an **Error Dialog Box** with the following message:
`Unhandled exception in script`
`Failed to execute script 'run' due to unhandled exception: DLL load failed while importing QtGui: The specified procedure could not be found.`

`Traceback (most recent call last):`
  `File "run.py", line 1, in <module>`
  `File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module`
  `File "registryspy\registryspy.py", line 3, in <module>`
`ImportError: DLL load failed while importing QtGui: The specified procedure could not be found.`

**Comment by andyjsmith** [comment]
Please see the supported platforms for Qt 6, Windows 10 1809 or newer is required. Unfortunately I would rather keep the dependencies updated to support modern features compared to supporting EOL OS versions.
https://doc.qt.io/qt-6.5/supported-platforms.html
